# Generated by Django 3.1 on 2022-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_bookcontent_bookorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_agg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=150)),
                ('isbn13', models.CharField(max_length=150)),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.BigIntegerField()),
                ('text_review_count', models.BigIntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=250)),
            ],
        ),
    ]
